# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'TGCameraViewController'
pod 'AFNetworking'
pod 'Parse'
pod 'NYTPhotoViewer'
pod "youtube-ios-player-helper", "~> 0.1.3"